spring:     
  datasource:
    url: jdbc:postgresql://localhost:5432/onlineschooldb
    username: onlineschooldb_user
    password: onlineschooldb_user_passwd
    hikari:
        connectionTimeout: 20000
        maximumPoolSize: 5
server:
    port: 9090